name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine the Docker tags
        id: get_tags
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "::set-output name=ghcr_tag::ghcr.io/${{ github.repository }}:latest"
            echo "::set-output name=dockerhub_tag::docker.io/${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest"
          elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "::set-output name=ghcr_tag::ghcr.io/${{ github.repository }}:dev"
            echo "::set-output name=dockerhub_tag::docker.io/${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:dev"
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.get_tags.outputs.ghcr_tag }}
            ${{ steps.get_tags.outputs.dockerhub_tag }}
          platforms: linux/arm/v7

